create extension if not exists pgcrypto;

create table if not exists public.products (
 id bigint generated by default as identity primary key,
 name text not null,
 price numeric(10,2) not null check(price>=0),
 stock integer not null default 0 check(stock>=0),
 icon text default '🚗',
 active boolean not null default true,
 created_at timestamptz not null default now()
);

create table if not exists public.orders (
 id uuid primary key default gen_random_uuid(),
 order_number text unique not null default ('CZ-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),
 customer_name text not null,
 phone text not null,
 email text,
 county text not null,
 city text not null,
 address text not null,
 payment_method text not null check(payment_method in ('cod','card')),
 total numeric(10,2) not null check(total>=0),
 status text not null default 'new' check(status in ('new','confirmed','shipped','completed','cancelled')),
 created_at timestamptz not null default now()
);

create table if not exists public.order_items (
 id bigint generated by default as identity primary key,
 order_id uuid not null references public.orders(id) on delete cascade,
 product_id bigint not null references public.products(id),
 name text not null,
 unit_price numeric(10,2) not null,
 quantity integer not null check(quantity>0)
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Catalogul activ poate fi citit public.
drop policy if exists "public read active products" on public.products;
create policy "public read active products" on public.products
for select to anon, authenticated using (active=true);

-- Comenzile pot fi create de vizitatori.
drop policy if exists "public create orders" on public.orders;
create policy "public create orders" on public.orders
for insert to anon, authenticated with check (true);

drop policy if exists "public create order items" on public.order_items;
create policy "public create order items" on public.order_items
for insert to anon, authenticated with check (true);

-- IMPORTANT:
-- Nu adăuga politici publice de UPDATE/DELETE pentru produse/comenzi.
-- Pentru admin, folosește autentificare Supabase și politici restrictive.
-- În producție recomandăm o tabelă admin_users și politici bazate pe auth.uid().
insert into public.products(name,price,stock,icon) values
('Încărcător auto 100W USB-C + USB-A',39.99,60,'🔌'),
('Cablu USB-C → USB-C 1m 60W',24.99,10,'🔋'),
('Cablu USB-C → USB-C 2m 60W',34.99,10,'🔋'),
('Suport magnetic telefon auto',29.99,20,'📱'),
('Cablu USB-C → Lightning 1m',29.99,5,'⚡'),
('Cablu USB-C → Lightning 2m',39.99,5,'⚡'),
('Kit curățare auto 5 piese',44.99,10,'🧽'),
('Lavete microfibră auto — 10 buc.',29.99,10,'🧼');
